# Generated by Django 5.1.1 on 2025-12-21 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_activityupload_activitydata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd')])),
                ('week_min', models.IntegerField()),
                ('week_max', models.IntegerField()),
                ('content_type', models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('emotional', 'Emotional'), ('warnings', 'Warnings')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_safe', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmp_date', models.DateField(verbose_name='Last Menstrual Period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
