# Generated by Django 5.1.1 on 2025-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_pregnancycontent_pregnancyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancyprofile',
            name='lmp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
