# Generated by Django 5.1.1 on 2025-12-21 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_pregnancyprofile_lmp_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitydata',
            name='upload',
        ),
        migrations.AlterField(
            model_name='pregnancycontent',
            name='content_type',
            field=models.CharField(choices=[('tip', 'Tip'), ('warning', 'Warning'), ('info', 'Information')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pregnancycontent',
            name='trimester',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('patient', 'Patient')], default='patient', help_text='User role for access control', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
