# Generated by Django 5.1.1 on 2025-12-21 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_remove_activitydata_upload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('patient', 'Patient'), ('doctor', 'Doctor/Physiotherapist')], default='patient', help_text='User role for access control', max_length=10),
        ),
        migrations.CreateModel(
            name='HealthVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField(help_text='Heart rate in BPM (60-100 normal, higher in pregnancy)')),
                ('spo2', models.IntegerField(help_text='Blood oxygen saturation percentage (95-100 normal)')),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Perceived stress level', max_length=10)),
                ('fatigue_level', models.IntegerField(help_text='Fatigue level on 0-100 scale (higher = more fatigued)')),
                ('daily_active_minutes', models.IntegerField(default=0, help_text='Active minutes accumulated today')),
                ('is_simulated', models.BooleanField(default=True, help_text='Indicates if data is simulated (not from real device)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Vital',
                'verbose_name_plural': 'Health Vitals',
                'db_table': 'health_vitals',
                'ordering': ['-timestamp'],
            },
        ),
    ]
