# Generated by Django 5.1.1 on 2025-12-22 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_alter_userprofile_role_healthvitals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('exercise_reminder', 'Exercise Reminder'), ('exercise_complete', 'Exercise Completed'), ('health_alert', 'Health Alert'), ('milestone', 'Pregnancy Milestone'), ('achievement', 'Achievement'), ('doctor_alert', 'Doctor Alert'), ('system', 'System Notification')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='exercise_no_user_id_e287b3_idx'), models.Index(fields=['user', 'is_read'], name='exercise_no_user_id_a0ccc5_idx')],
            },
        ),
    ]
