# Generated by Django 5.1.1 on 2025-12-22 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('inactive_user', 'Inactive User (3+ days)'), ('streak_milestone', 'Streak Milestone'), ('new_content', 'New Content Available'), ('health_tip', 'Daily Health Tip'), ('pregnancy_week', 'Pregnancy Week Milestone'), ('achievement', 'Achievement Unlocked'), ('welcome_back', 'Welcome Back'), ('weekly_summary', 'Weekly Summary Ready')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trigger_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_engagement', models.BooleanField(default=True, help_text='Receive engagement notifications')),
                ('enable_email', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('enable_reminders', models.BooleanField(default=True, help_text='Receive custom reminders')),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('enable_health_alerts', models.BooleanField(default=True)),
                ('enable_exercise_reminders', models.BooleanField(default=True)),
                ('enable_pregnancy_tips', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='CustomReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('medicine', 'Medicine'), ('appointment', 'Appointment'), ('exercise', 'Exercise'), ('water', 'Water Intake'), ('meal', 'Meal'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('scheduled_time', models.TimeField(help_text='Time to send reminder (HH:MM)')),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('days_of_week', models.JSONField(default=list, help_text='For weekly: [0,1,2,3,4,5,6] where 0=Monday, 6=Sunday')),
                ('is_active', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False, help_text='Send email notification')),
                ('send_notification', models.BooleanField(default=True, help_text='Send in-app notification')),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='exercise_cu_user_id_eea79e_idx'), models.Index(fields=['scheduled_time'], name='exercise_cu_schedul_a3d44d_idx')],
            },
        ),
    ]
