# Generated by Django 5.1.1 on 2025-12-22 14:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_engagementnotification_notificationpreferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Nutrition Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('trimester', models.IntegerField(choices=[(1, 'First Trimester'), (2, 'Second Trimester'), (3, 'Third Trimester'), (0, 'All Trimesters')], default=0)),
                ('icon', models.CharField(default='💡', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Nutrition Tips',
                'ordering': ['order', 'trimester'],
            },
        ),
        migrations.CreateModel(
            name='NutritionFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nutrition/')),
                ('description', models.TextField()),
                ('calories', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('benefits', models.TextField(help_text='Why this food is good for pregnancy')),
                ('serving_size', models.CharField(default='100g', max_length=100)),
                ('trimester_recommended', models.JSONField(default=list, help_text='List of recommended trimesters [1,2,3]')),
                ('warnings', models.TextField(blank=True, help_text='Any precautions or warnings')),
                ('rich_in', models.JSONField(default=list, help_text='["Iron", "Calcium", "Folic Acid"]')),
                ('is_recommended', models.BooleanField(default=True)),
                ('is_avoid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='exercise.nutritioncategory')),
            ],
            options={
                'verbose_name_plural': 'Nutrition Foods',
                'ordering': ['category', 'name'],
            },
        ),
    ]
