# Generated by Django 5.1.1 on 2025-12-22 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_nutritioncategory_nutritiontip_nutritionfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Primary doctor/OB-GYN', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full legal name', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital',
            field=models.CharField(blank=True, help_text='Hospital or clinic', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lmp_date',
            field=models.DateField(blank=True, help_text='Last Menstrual Period date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Pre-existing medical conditions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pre_pregnancy_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight before pregnancy in kilograms', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_pregnancies',
            field=models.IntegerField(default=0, help_text='Number of previous pregnancies', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kilograms', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
