# Generated by Django 5.1.1 on 2025-12-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_userprofile_allergies_userprofile_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Doctor's full name", max_length=200)),
                ('specialization', models.CharField(default='Obstetrics & Gynecology', max_length=100)),
                ('hospital', models.CharField(help_text='Primary hospital/clinic', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doctors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('health', 'Health'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('symptoms', 'Symptoms')], default='general', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Article content in markdown format')),
                ('category', models.CharField(choices=[('trimester', 'Trimester Guide'), ('health', 'Health & Wellness'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('preparation', 'Birth Preparation')], max_length=50)),
                ('trimester', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], help_text='Specific trimester (leave blank for all)', null=True)),
                ('week_number', models.IntegerField(blank=True, help_text='Specific week number (leave blank for general content)', null=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guidance_articles',
                'ordering': ['order', 'trimester', 'week_number'],
            },
        ),
    ]
